### ISSUE TITLE
Cannot disable Auto-Formatting 

### ISSUE THREAD

**Issue by mprobst** [Microsoft/TypeScript-Sublime-Plugin#105]
According to the docs, auto-formatting should be disabled by default. However it seems to be *enabled* by default - after installing the plugin, when I type `;` or `{` I do get formatting (with +4 indentation, not matching my editor settings...).

Additionally, I did add `"typescript_auto_format": false` to my Preferences.sublime-settings, but that doesn't seem to disable the formatting either.

**Comment by steveluc** [comment]
Hi @mprobst.   You probably didn't get a chance to see the Tips part of the README.md as we just checked it in yesterday.  Below is the prose about the behavior.  To summarize: Enter is Sublime auto indent by default, but ';' and '}' are TypeScript format by default.   'typescript\_auto\_format' is definitely a confusing name since it's auto indent that is toggled.  We will add a 'typescript\_auto\_indent' setting and have this control Enter.  Then we can make the 'typescript\_auto\_format' setting control ';' and '}'.  Which editor setting did you use for indentation size?  The plug-in tries to follow 'tab_size', because that's what Sublime auto indent uses. 

5. By default, the plug-in retains the Sublime native behavior for
   auto indent (such as when typing the Enter key).  To have the
   TypeScript server supply auto indent, set the
   'typescript\_auto\_format' setting to true in your
   Preferences.sublime-settings file.  The plug-in does by default
   request TypeScript formatting upon typing ';' or '}'.  You can turn
   off TypeScript formatting on these characters by removing the key
   bindings from the Default.sublime-keymap file in the TypeScript
   package.

**Comment by steveluc** [comment]
Also would like to get more comments on defaults.  We could turn off ';' and '} by default.  The formatting would still be available by typing 'ctrl + ;' (format line) and 'ctrl + }' (format block).  So far most people testing have requested these on by default.

**Comment by steveluc** [comment]
'typescript\_auto\_indent' added and 'typescript\_auto\_format' changed to apply to formatting on ';' and '}'.  For now, defaults are false for indent and true for format.  You can override either in User\Preferences.sublime-settings.    README.md tip updated.

Commit f5bfc98.

**Comment by mprobst** [comment]
I think I might have misread the `README.md`, the distinction between auto format and auto indent escaped me ;-) With your commit, I can easily disable the auto formatting now, so I have the exact behaviour I want, thanks.

Regarding defaults: I think it's very useful to have a quick-to-trigger auto-formatter, e.g. with a keybinding that formats the current statement or scope. I'm not entirely convinced about auto-formatting during regular typing (with `{`, `;` etc), that might be more disruptive than helpful for me, but YMMV.

I might also be a bit of a special case as I use [clang-format](http://clang.llvm.org/docs/ClangFormat.html) to format both my JavaScript and TypeScript code (and C++, for that matter). It's a bit more feature complete than TS' built in formatting, e.g. it wraps overlong lines, realigns arguments, etc.

I'll close this issue as the auto-formatting can now be easily disabled.
