### ISSUE TITLE
Could not find from Package Manager

### ISSUE THREAD

**Issue by jeffbcross** [Microsoft/TypeScript-Sublime-Plugin#107]
Sublime Version: Sublime Text 3 
Platform: Mac OSX

Steps:
 * Package Control > Install Package
 * Type: typescriptlang
 * No results

Note I had previously installed from git, from the https://github.com/Microsoft/ngconf2015demo repository. But I'd since removed the package via package manager, and restarted Sublime.

**Comment by jeffbcross** [comment]
Oops! I just saw the note about package pending approval

**Comment by ddotlic** [comment]
5 days later, this is still supposedly pending approval. Personally, it's not too difficult for me to get this via git, but keeping it up to date is slightly annoying (must not forget to git pull from time to time where packages update automatically).

Is there a reason for this delay?

**Comment by billti** [comment]
It took a few days for them to look at the pull request, so that caused most of the delay so far.  Now the maintainer has actually pinged the owner of 'TypeScript' package to see if we can take that name (seeing as that one is just a syntax file and has been stagnant for a while), rather than us needing to use something else not taken (hence the `TypeScriptLang` name currently proposed).  See https://github.com/wbond/package_control_channel/pull/4280 

I totally feel you.  We're very keen to get this on Package Control also, but if we are able to get the more relevant name, it would be worth it long term.

**Comment by ddotlic** [comment]
@billti Yeah, using Typescript name is worth it IMHO. Thanks for the details!
