### ISSUE TITLE
No syntax highlighting for primitive class members on a succeeding line.

### ISSUE THREAD

**Issue by bunnycode** [Microsoft/TypeScript-Sublime-Plugin#150]
![screen shot 2015-04-16 at 10 13 37 am](https://cloud.githubusercontent.com/assets/2212259/7182757/768e979a-e421-11e4-8b6a-3466fcfe5d9a.png)

**Comment by bunnycode** [comment]
Looks like this also affects multi-line object literals as well:

![screen shot 2015-04-16 at 10 28 35 am](https://cloud.githubusercontent.com/assets/2212259/7183102/7f9372c8-e423-11e4-83fd-3a97d158aef5.png)

**Comment by zhengbli** [comment]
This is due to a syntax definition error for object fields declaration. Related fix PR #155

**Comment by steveluc** [comment]
:+1:  Great!

**Comment by zhengbli** [comment]
Actually, the fix in PR #155 will not work without line ending delimiter (; / , / }) (the case mentioned in issue #149), because our solution for addressing #149 treats the new line character as a delimiter. A fix for both cases is hard and probably low priority for us, because there are many functioning bugs to fix at the moment. However it is definitely on the road map as we migrate to the new syntax definition format that Sublime 3 announced recently, which allows for more powerful syntax rules. 

Between the two cases, the other one seems to have higher priority, because a number of JavaScript developers prefer not to use semicolons; and putting the assigning value in different lines from the assigned variable is non-standard behavior anyways. Therefore for now the issue in your first screenshot will not be fixed, but the issue in your second screenshot will. Thanks for contributing!
