### ISSUE TITLE
Jump Back doesn't work after Goto Definition

### ISSUE THREAD

**Issue by tsteele3rt** [Microsoft/TypeScript-Sublime-Plugin#154]
When jumping back (Ctrl + -) after going to a definition (Ctrl + t, Ctrl + d), it does not return to the item you were on when using Goto Definition from this plugin.

It seems to possibly jump back to a previous location. So maybe the plugin needs to explicitly update the current location before going to definition???

**Comment by zhengbli** [comment]
Actually after some experiment, I tend to think this is a sublime bug (or intentional behavior). Sublime will change the current location with some behavior, and unfortunately I haven't found any API to explicitly add the current location to the location history stack.

I tried 2 cases:
Case 1: in a non-ts file with the plugin disabled, click on one location (L1), then click on another (L2), then use the arrow keys to navigate to somewhere else (L3), then call "jump back". The cursor will jump to the L1 instead of L2;
Case 2: I tested the "go to definition" function in a python file using the anaconda plugin (reason is they implemented the function similarly), the same problem (jumping to previous location) appears too.

I'll try to find if there are any workaround to insert the current location in the history stack, but the problem is more likely to be sublime itself.
