### ISSUE TITLE
TypeScript plugin cause sublime 3 hang up

### ISSUE THREAD

**Issue by systembugtj** [Microsoft/TypeScript-Sublime-Plugin#167]
install the plugin on mac(yosemite 10.10.3) for sublime 3 (3083)
open one .ts file, make sure you some reference like ///
enter this. 

then sublime hangup forever.

**Comment by zhengbli** [comment]
Sorry about the perf problem. Can you do the following to generate a log file to help us identify the root issue:
1. open the "TypeScript.py" file in your package folder, change the ``logFileLevel = logging.WARN`` to ``logFileLevel = logging.DEBUG``
2. repeat the procedure that causes the hang, then close sublime text
3. post the content of TS.log in your package folder.

**Comment by elyulka** [comment]
I have similar issue on OS X Yosemite 10.10.3. Sublime starts to use 100% cpu.
TS.log if continuously filled with:

> 2015-05-03 14:14:30,580: 4402802688: INFO: 0 byte line in stream when expecting header
2015-05-03 14:14:30,580: 4402802688: DEBUG: Stream state: "init".  Read header: "None"

**Comment by elyulka** [comment]
Same happens in Sublime on Ubuntu 14.04LTS.

**Comment by ddotlic** [comment]
I'm seeing the same or very similar on Windows 8.1 64-bit, running current master code. I have no triple slash references in any of my TS files. This happens _only_ on startup.

CPU spikes, occasionally I actually get a crash (trying to copy error text, but CPU is pegged) then lots of (like above) `0 byte line in stream when expecting header`. Just saw that I should enable debugging, which I just did, waiting for next crash to post the log.

I am running TypeScript 1.5 beta installed through NPM and verified to be first on a path.

If I would guess, this only happens when I restart Sublime due to the need for TS to recognize newly added files.

As-is, I usually have to restart Sublime 3 twice before things stabilize, the second time it works fine.

And, of course, now that I've enabled debugging I can't make it crash any more :smile:

**Comment by steveluc** [comment]
Commit c23ada9 adds a check that exits the reader loop if the node process has exited.  This fixes both the reload problem and the case where node or the tsserver.js file are not found.  Please let us know if it does not fix your case.

**Comment by ddotlic** [comment]
I have not seen the issue in the last three days or so, most likely it has been fixed. I suggest you close this, we can always reopen if the problem re-appears.

**Comment by systembugtj** [comment]
Thanks for the fix. I will try it asap.

**Comment by KhaledMohamedP** [comment]
the same here on my mac

**Comment by justin-rosecrans** [comment]
I currently get 3 sublime programs running with 97% CPU usage.

**Comment by zhengbli** [comment]
@justin-rosecrans I noticed that the sublime package control uses very high CPU when working on large git repos. Did you try disabling the plugin and see if the high CPU usage still exists? Thanks

**Comment by justin-rosecrans** [comment]
@zhengbli I removed the plugin and it still continued to be running the 3 processes. So I had to force stop the processes on the activity monitor. Then it went away.

**Comment by zhengbli** [comment]
then it is a sublime issue rather than a plugin issue, which I personally experienced as well.

Zhengbo

**Comment by justin-rosecrans** [comment]
That's what I'm thinking as well now. Thanks for responding back to me.
