### ISSUE TITLE
cannot import modules

### ISSUE THREAD

**Issue by itajaja** [Microsoft/TypeScript-Sublime-Plugin#207]
If i use the `-m commonjs` option from cli then I can do this in the code:

````js
import {Component, View, bootstrap} from 'angular2/angular2';
````

but in ST the plugin marks the line as an error saying:

 > Cannot compile external modules unless the '--module' flag is provided

how do I provide command line options to the plugin?

**Comment by billti** [comment]
To specify options for the editor that you would normally specify on the command-line for the compiler, add a tsconfig.json file to the directory (or a parent directory) of your code.  The Sublime plugin for TypeScript will use the settings in this file.  See https://github.com/Microsoft/TypeScript/wiki/tsconfig.json

**Comment by itajaja** [comment]
Oh. Thanks :) Do you think it's a welcomed PR if I make this more visible in the readme of the ST plugin?

**Comment by robertdp** [comment]
> add a tsconfig.json file to the directory (or a parent directory) of your code.

@billti, I'm still getting that error even with the file, but only when editing files that are 2 or more folders deep. It seems as though the plugin is only looking in the file's current folder and the one above that.

There are no errors when compiling the project, but Sublime has red squiggles in almost every file.

**Comment by SummerWish** [comment]
my typescript compiler even does not lookup `tsconfig.json` in the file's current folder :-( However typing `tsc` in the terminal is okay.

**Comment by ulritech** [comment]
I also had problems with this plugin working for files that were deeply nested in the directory structure. I use webpack and had originally set the tsconfig files to 2 files: my entry point and my typings file. With this configuration, sublime showed red squiggles everywhere and the typescript auto completion feature did not work.

Somewhere, I recalled a user reporting that *this plugin worked as expected if every ts file in his project was listed in the tsconfig files array* (and he suggested using gulp to keep this in sync). Sure enough, **listing each ts file in the tsconfig files array works** - the red squiggles no longer appear and auto completion also works.

The [ArcticTypescript](https://packagecontrol.io/packages/ArcticTypescript) package describes a **filesGlob property that can use wildcards**. I replaced the files property with filesGlob as they describe and boom - everything started working for all my files **without the need for a gulp workflow to update this automatically**.

``` json
{
	"compilerOptions": {
		"module": "commonjs",
		"noImplicitAny": true,
		"sourceMap": true,
		"removeComments": false,
		"target": "es5"
	},
	"filesGlob": [
		"./**/*.ts",
		"!./node_modules/**/*.ts"
	],
	"exclude": [
		"node_modules",
		"dist"
	]
}
```

**Comment by Bartzy** [comment]
@ulritech 
This works for me - thanks!

**Comment by zhengbli** [comment]
@SummerWish This is because your `tsconfig.json` didn't include your `vj4.ts` file in your project. Therefore when you try to build the `vj4.ts` in the plugin, the compiler complains because the file doesn't belong to a configured project. However, when you run `tsc` in the command line, your are only compiling the `typings/tsd.d.ts`, and it is understandable why it was done successfully. 

To solve the issue, as @ulritech suggested above try to add *all source files* of your project in your `files` array, or do not specify a `files` array to implicitly include every files in the directory. More information can be found at the [wiki page](https://github.com/Microsoft/typescript/wiki/tsconfig.json)

**Comment by Bartzy** [comment]
@zhengbli I used the filesGlob config @ulritech provided above, and it works. I didn't find documentation for filesGlob - Is it supported publicly?

Thanks.

**Comment by zhengbli** [comment]
There is an open PR for the filesGlob support (https://github.com/Microsoft/TypeScript/pull/5980), though it is not merged in yet. The one came with `Arctic​Typescript` is their own implementation I believe.

**Comment by Bartzy** [comment]
That's weird - How my config works then?

```
{
    "compilerOptions": {
        "module": "es6",
        "target": "es6",
        "sourceMap": true,
        "noImplicitAny": true,
        "removeComments": false
    },
    "filesGlob": [
        "./**/*.ts",
        "!./node_modules/**/*.ts"
    ],
    "exclude": [
        "node_modules",
        "dist"
    ]
}
```

**Comment by zhengbli** [comment]
It probably is a coincident. Assuming you are not using the `ArcticTypeScript` plugin, the `filesGlob` property will be discarded by the language service because it is not supported. Then it is the equivalent to a tsconfig file without `files` array, therefore all source files except folder / files in the `exclude` list will be included. And if you have `//// <reference/>` in your code for the `ts` files within `node_modules` folder, those will be included too.

**Comment by Bartzy** [comment]
Got it.

So for now, until filesGlob is supported, I should include all files I want to compile in the files array?

**Comment by zhengbli** [comment]
You can, though you definitely can do without the files array and implicitly include every ts files in the folder, and put stuff you don't want in the exclude array, if that works for you.

Zhengbo
