### ISSUE TITLE
Grammer produces endless loop in first-mate

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript-Sublime-Plugin#229]
First-mate is the text mate implementation used in Atom and VS Code. The following code snippet produces an endless loop in first-mate:
```
class MyClass {
    template = '' +
               '<a> {}</a>';
}
```

The problematic grammer part is: method-declaration. 

The method declaration enter and consumes '<a> {} 

The it interprets < as a type parameter again in a method-declaration, consume nothing (the entry is done using a look ahead and then leave the method declaration the a look back for }. The result is the the method-declaration rule didn't consume anything and it enter again.

Another problem is with field declarations which a left on new line. That is why the grammer dasn't recognize the code as a field with an initializer expression.

The problem doesn't show up in Sublime. Sublime seems to protect itself against loop rules.

**Comment by zhengbli** [comment]
I'm not sure I follow. What is the issue if Sublime doesn't have this problem?

**Comment by dbaeumer** [comment]
If you use the grammar inside Atom or VS Code (as we do) opening a file with the above text makes the first-mate code loop forever. We are working on a PR for first-mate to handle that more gracefully. However a grammar that have rules that don't consume anything are always dangerous.

**Comment by alexandrudima** [comment]
The grammar rules trigger an infinite loop. It reaches a case where it enters a rule, then pops it, then enters it again, etc, all without advancing the stream. Sublime most likely has written code especially to protect against grammars with similar infinite loops patterns. IMO, the fact that Sublime doesn't show a problem does not mean that the grammar is bug-free, it just means that Sublime has code that protects itself against grammars with this bad behaviour.

The module we're reusing for VSCode (the same one atom uses, First-Mate) lacked such protection for this specific case. See https://github.com/atom/first-mate/pull/47

In any case, the fact that atom is shipping since 1.5 years and loading many different TM syntaxes without such a check until now shows that such an issue is rare (they didn't encounter it before, i.e. none of the other grammars ever loaded in atom had such an infinite loop pattern).

IMHO, the way forward is for First-Mate to add more checks to protect against such loops (see the PR) and for the TypeScript grammar to be fixed. Personally, I did not understand the intent of how the TypeScript grammar is authored around method-declaration to propose a PR to fix the looping.

**Comment by hoanhtien** [comment]
@dbaeumer @alexandrudima I am looking into this issue. I configure VSCode and Atom to use the grammar and they seem fine; neither editor hangs. How can I know if there is an endless loop?

**Comment by alexandrudima** [comment]
@hoanhtien We've since patched VSCode to identify and skip the line that enters the endless loop in this case. You can see something is wrong when opening a .ts file containing the text mentioned originally and pressing `F1` and choosing `Developer: Toggle Developer Tools`. You can then see the error the grammar interpreter prints:

`Skipping line because rule loops at column 22 of line '               '<a> {}</a>';' Array[3]`

We've mitigated this in the grammar interpreter, but IMHO it's still a bug in the grammar.

**Comment by hoanhtien** [comment]
This problem is fixed in https://github.com/Microsoft/TypeScript-Sublime-Plugin/pull/307 which was checked in to master earlier today. This pull request parses everything between quotes i.e `<a>{}</a>` as a string. As a result, {} will no longer be consumed by the method-declaration rule and that will avoid the endless loop.

Before:
![image](https://cloud.githubusercontent.com/assets/1707813/8915477/0992e068-345a-11e5-8586-5c7ca4e6efd5.png)

Now:
![image](https://cloud.githubusercontent.com/assets/1707813/8915482/166368ee-345a-11e5-8aed-38bec7a567da.png)

**Comment by alexandrudima** [comment]
@hoanhtien Great, thank you!
