### ISSUE TITLE
Typing quickly in a argument list can cause the popup to disappear

### ISSUE THREAD

**Issue by billti** [Microsoft/TypeScript-Sublime-Plugin#233]
This appears to be a timing issue.  Typing slowly this rarely happens.  It looks like getCompletions is returning no results for the current position.  (Perhaps it is asking for completions on a position before the edits in the buffer have been processed?).

It appears to happen most often after entering a line-break in the middle of an arg list.

**Comment by hoanhtien** [comment]
To keep the buffer content of the client side in sync with that of the server side, the plug-in constantly checks the last command in command history and if it is an `insert` command, performs the following logic:
(1) If the command inserts an `\n`, mark the buffer as "in need of reload". The `reload` request will be send later in the event handler for event `on_post_text_command_with_info`.
(2) If the command inserts other characters, immediately send a `change` request to `tsserver`.

When user enters a line-break i.e. `\n` then quickly follows up with some characters, for example: `123`. The line-break and these character i.e. `\n123` will be combined in the last command in the command history. Therefore, and due to (2), typing `123` will not send a `change` request. (3)

Event `on_post_text_command_with_info` is only triggered by sublime when user types the `\n`. Typing `123` does not send any `reload` request. (4)

Due to (3) and (4), the insertion of characters `123` are never sent to the server. Hence we got this error.

Fixing this bug by ensuring a `reload` request is send before every signature request.
