### ISSUE TITLE
Include .d.ts file for code completion

### ISSUE THREAD

**Issue by amritk** [Microsoft/TypeScript-Sublime-Plugin#256]
I couldn't find much documentation on the .tsconfig.json file, but is it possible to reference a definition file for the project? Right now I have one .d.ts file that references everything, referenced in my grunt config, so I don't need to include it at the top of every file. It compiles fine, but I was wondering if I can get sublime to read this file so I can get proper code completion without having to include that extra reference line at the top of every file.

I tried throwing it into the tsconfig but I don't think that did anything.
```
{
    "files": [
        "app/assets/definitions/typings/tsd.d.ts"
    ]
}
```

**Comment by zhengbli** [comment]
The documentation of ``tsconfig.json`` can be found at https://github.com/Microsoft/TypeScript/wiki/tsconfig.json. You have to include both your file and the .d.ts file in the ``files`` array though, otherwise your file referring to the .d.ts file will be excluded from the configured project, which causes no information taken for auto completion.

**Comment by amritk** [comment]
Thanks
