### ISSUE TITLE
Copy+Paste broken for TS Files

### ISSUE THREAD

**Issue by danmane** [Microsoft/TypeScript-Sublime-Plugin#309]
After installing this plugin, I find that paste is broken (only for Typescript files). Pressing cmd+v has no effect.  I see that the plugin has overwritten cmd+v to paste and format. It appears that this functionality is not working as intended.

**Comment by danmane** [comment]
Actually, it may be that the typescript language services died entirely, which knocked out paste functionality as a side-effect.

**Comment by hoanhtien** [comment]
Doesn't work indeed, even on Windows. This is a bug.

**Comment by hoanhtien** [comment]
@danmane The reason it does not work on Windows is because we overwrite Cmd+v and Windows does not have a Cmd key. It is a separate problem to what you are having (I assume you are using MAC).
```
    {
        "keys": [ "super+v" ],
        "command": "typescript_paste_and_format",
        "context": [
            { "key": "setting.typescript_auto_format", "operator": "equal", "operand": true },
            { "key": "selector", "operator": "equal", "operand": "source.ts" }
        ]
    }
```
We check on a MAC and Cmd+V works without problem. Could you confirm that typescript language service server is dead (symptoms: error messages on the Python console, auto-completion does not work, format-document does not work)?

Also have you tried to fully quit Sublime (using the Quit command on the application menu) and restart? This will restart the typescript server.

A work-around is to disable auto format by setting `"typescript_auto_format": "false"` and use `Ctrl + T`, `Ctrl + F` to manually format the whole document.

**Comment by danmane** [comment]
@hoanhtien I can confirm that when it stopped working for me, it was because the Typescript server was dead. I was using sublime tunneling over SSH to modify a typescript project on a remote server, and the connection was flaky.

Closing the issue.

**Comment by mgiraldo** [comment]
@danmane how did you fix this? i have Cmd+V not working in my Mac also. i am compiling manually via `tsc -w`

**Comment by mgiraldo** [comment]
never mind. i restarted Sublime and it worked again. thanks.

**Comment by asimlqt** [comment]
This is definitely a bug. I have the same problem on Linux, Ctrl+V does not work in typescript files. Works fine in regular javascript files.

Disabling auto formatting as mentioned by @hoanhtien worked for me. Thanks.

**Comment by shudson250** [comment]
Disabling auto formatting as mentioned by @hoanhtien worked for me as well.

To save you from digging through settings files, just add `"typescript_auto_format": false,` to
Package Settings > Typescript > Plugin Settings

**Comment by zhengbli** [comment]
@shudson250 does other functions of this plugin work for you at the moment, namely intellisense, find-all-references, rename etc.? We saw people reporting that the plugin wasn't working on Sublime build 3103 (#452), so if you have the same issue maybe we can get more input.

**Comment by shudson250** [comment]
@zhengbli It's been a while here but I've been able to work with the quick fix I mentioned. Finally able to put some time to this issue. Previously I did not have intellisense

I deleted the TypeScript packages folder from AppData (on Windows) and reinstalled the Plugin using command line instruction specified in the repo here. Seems to have fixed all the issues I had with the plugin.

**Comment by Bartzy** [comment]
Hi,

Copy-Paste doesn't work for me on OS X El Capitan (10.11.2) and Sublime 3 (Build 3103).

Any fix besides disabling auto formatting?

Thanks.

**Comment by zhengbli** [comment]
Update: 
the reason why copy / paste is not working is very likely due to file casing problems that caused the server to crash. We decide file system case sensitivity using the platform, so if using a different file system from the default OS option, it will break. In addition, files on mounted network file systems can cause crash too. Unfortunately if this happens to you, for now the best workaround is to disable auto-formatting. If neither condition applies to you, please reply with detail.

I am working on the fixes for both issues and will draft a new release after the fixes.

**Comment by Bartzy** [comment]
@zhengbli I'm using OS X and the filesystem is HFS+. It is not on a network filesystem.

Thanks.

**Comment by zhengbli** [comment]
@Bartzy are you on a case-sensitive or insensitive version of HFS+?

**Comment by Bartzy** [comment]
@zhengbli Just checked, no.

**Comment by zhengbli** [comment]
That's expected, currently the TS language service doesn't work without a physical file on the disk. Work around is as suggested in https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/309#issuecomment-192068458. In the next release the autoformat will be default to false.

**Comment by Bartzy** [comment]
OK, thanks.

What exactly does that auto-formatting feature does that Sublime doesn't do already?

**Comment by tchoulihan** [comment]
This issue shouldn't be closed, I'm still getting it.
