### ISSUE TITLE
Snippets stop working in TypeScript files

### ISSUE THREAD

**Issue by bjnsn** [Microsoft/TypeScript-Sublime-Plugin#369]
Snippets seem to be clobbered by the most recent version of the plugin on PackageControl + NPM typescript install. It's possible I'm missing something - so please comment if it works for you. When I provide SublimeText (v3) a snippet (without a source scope) it works across other languages (JS, python, etc). Simple test case:

    <snippet>
        <content><![CDATA[
    class ${1:name} {
        constructor() {}
    }
    
    ]]></content>
        
        <tabTrigger>tsclass</tabTrigger>
        
        
    </snippet>

**Comment by hoanhtien** [comment]
This can be fixed by using `'api_completions_only': True` in the following line:
https://github.com/Microsoft/TypeScript-Sublime-Plugin/blob/b9f3b14fc4b573c3d3292cbc7f009dd0d8c3a89a/typescript/listeners/completion.py#L147

Looks like this problem has been there for a long time (in Sublime 3 only - works fine in Sublime 2).
