### ISSUE TITLE
support of typescript npm modules

### ISSUE THREAD

**Issue by stepancar** [Microsoft/TypeScript-Sublime-Plugin#370]
Hello! Thank you for this plugin.
[Atom-typescript](https://github.com/TypeStrong/atom-typescript) supports go-to definitions for typescript npm modules. This is awesome.
Please add support of this feature to sublime.
More info [here](https://basarat.gitbooks.io/typescript/content/docs/node/nodejs.html)
and this is [example](https://github.com/basarat/ts-npm-module-consume) - how to create npm module. 
Now, as i understand,  TypeScript-Sublime-Plugin is not support this feature.

**Comment by stepancar** [comment]
@zhengbli, whats status of this issue? As i understand this project, obsolete outdated?

**Comment by zhengbli** [comment]
At first glance I thought this issue was about supporting the `typescript` npm package as the language service, as recently addressed with #433. However after reading the example, now I get what you meant was to consume npm packages written directly in TypeScript. Sorry for the misunderstanding.

And regarding this feature you asked, it should already be supported. I tested the example repo you posted, `Goto definition` does jump to the right place in the `node_modules` folder. Can you give it a try?

**Comment by stepancar** [comment]
@zhengbli , thank you!
