### ISSUE TITLE
Destructuring assignment with new lines breaks the highlighting

### ISSUE THREAD

**Issue by altayaydemir** [Microsoft/TypeScript-Sublime-Plugin#496]
Hello, first of all thanks for making this plugin.

I come across to a syntax highlighting problem when I use new lines with the destructuring assignment. I'm not sure if its related with the plugin or typescript itself.

For the cases with just one line, it works fine:

<img width="698" alt="screen shot 2016-07-17 at 01 08 17" src="https://cloud.githubusercontent.com/assets/9790196/16897462/18c24abe-4bbb-11e6-9513-5ebf44934aa0.png">

However, when I want to use new lines inside destructuring it becomes like this:

<img width="282" alt="screen shot 2016-07-17 at 01 08 31" src="https://cloud.githubusercontent.com/assets/9790196/16897466/2d99e5f0-4bbb-11e6-9b11-7809d27188a1.png">

and here's another case

<img width="278" alt="screen shot 2016-07-17 at 01 08 55" src="https://cloud.githubusercontent.com/assets/9790196/16897469/3466b80e-4bbb-11e6-983f-0c1151e97a48.png">

I'm using Mac OS X, El Capitan with Sublime Text 3 (Build 3114) and the examples above taken from a `.tsx`file.

Do you have any idea or suggestions?

Thanks,
Altay

**Comment by DanielRosenwasser** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#211

**Comment by sunny-g** [comment]
I don't believe this is fixed in `.tsx` files as I'm still lacking syntax highlighting when destructuring objects and arrays over new lines:

![screen shot 2017-04-10 at 6 13 43 pm](https://cloud.githubusercontent.com/assets/2055636/24888608/75253132-1e19-11e7-8d5e-9397067e137c.png)

vs 

![screen shot 2017-04-10 at 6 12 34 pm](https://cloud.githubusercontent.com/assets/2055636/24888579/515c1bb2-1e19-11e7-9ddd-29c95f822a8b.png)

Do I need to configure something?
