### ISSUE TITLE
sublime experimental support for decorators warning even with experimentalDecorators set true

### ISSUE THREAD

**Issue by gregbown** [Microsoft/TypeScript-Sublime-Plugin#524]
On windows 10, Sublime text 3 build 3114, using Typescript 2.1.0-dev.20160921, node version 6.3.0, npm version 3.10.3, Working on Angular 2 project with latest release, I continue to get the warning in the footer "Experimental support for decorators is a feature that is subject to change in a future release. Set the experimentalDecorators option to remove this warning" and the squiggly line under class names or @ViewChild etc. despite having experimentalDecorators set to true.
I have the user setting pointing to my global version of typescript:
{
	"typescript_tsdk": "C:\\Users\\gbown\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib"
}
Please let me know if I am missing some configuration.
Thank you
Greg

**Comment by gregbown** [comment]
I also noticed that Array.slice and Array.map are no longer seen as valid.  Warning Property 'map' does not exist on type 'ArrayConstructor'. I tried rolling back to typescript 2.0.2 to no avail.
Any advice on this matter would be appreciated.
Thank you

**Comment by johndeighan** [comment]
I am also having this problem and it's getting quite annoying. I've seen some possible solutions on the Sublime Text forums, but they seem to just turn all TypeScript error checking off, which is not a solution. I'm using Windows 10, SublimeText 3 build 3126, TypeScript Version 1.9.0-dev.20160409 (because the book "ng-book 2" specifies it for its examples), node version 6.7.0, npm version 3.10.3, working on an Angular 2 app created with angular-cli.

I don't even know how to check if it's reading the tsconfig.json file that it should, but ignoring the experimentalDecorators key, or just not using the file at all.

**Comment by basherr** [comment]
I am also having the same issue same as @johndeighan  issue

**Comment by gregbown** [comment]
Alright, so the clarification that is missing is:

Pointing to your local version of typescript should be done in the global User settings 
NOT  Typescript Settings - User

Thanks to the clarification (Ctrl + Shift + P > Preferences: Settings) in http://stackoverflow.com/questions/39756578/angular-2-with-errors-in-sublime-text-3
