### ISSUE TITLE
Remove popups and hints in text area.

### ISSUE THREAD

**Issue by mafflin** [Microsoft/TypeScript-Sublime-Plugin#556]
Please add option to disable annoying popups and alerts.

**Comment by bjnsn** [comment]
If you're referring to this, then I (politely) second the need for control.

![screen shot 2016-10-31 at 4 57 58 pm](https://cloud.githubusercontent.com/assets/791610/19875601/444d347c-9f8b-11e6-8f84-ff03809397ef.png)

I thought this was the same as https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/544 but `show_errors_inline` doesn't seem to impact it.

**Comment by ledz3pp** [comment]
Absolutely agree. I had to manually edit the script to get rid of the annoying popup.
I also noticed that after recent changes my color scheme is broken now

**Comment by bypotatoes** [comment]
+1

**Comment by lorem--ipsum** [comment]
Who thought this could be a good idea ? If I wanted annoying popups with bright colors, I'd be using Webstorm.

**Comment by xaralis** [comment]
Please please, make this optional, the worst thing about it is that it makes your code lines jump back and forth and makes coding pretty creepy.

**Comment by roblav96** [comment]
#thisfeaturesucks lol

**Comment by PWKad** [comment]
@ledz3pp can you share what you did to get rid of this?

**Comment by bjnsn** [comment]
@PWKad Reverting to version 0.1.16 is one short-term option (worked for me).

**Comment by PWKad** [comment]
@bjnsn nice, I'll do that now as this is causing me to have a bunch of typos that I've never seen in Sublime before as the box shows and hides itself on in multi-line text mode.

**Comment by cdeutsch** [comment]
This makes sublime unusable. Revert

**Comment by KirillGrishin** [comment]
This is really annoying. I am pretty sure those who thought of it had best intentions in mind, but this is so annoying and distracting. Please please please, turn it off, or make optional.

**Comment by p-mcgowan** [comment]
To anyone else looking for the solution: comment lines 26 - 29 (inclusive) in `.../Packges/TypeScript/typescript/commands/error_info.py`
```
...
if len(error_text) > 0:
            # if PHANTOM_SUPPORT:
            #     template = '<body><style>div.error {{ background-color: brown; padding: 5px; color: white }}</style><div class="error">{0}</div></body>'
            #     display_text = template.format(error_text)
            #     self.view.add_phantom("typescript_error", self.view.sel()[0], display_text, sublime.LAYOUT_BLOCK)
            self.view.set_status("typescript_error", error_text)
```

**Comment by caiogondim** [comment]
What happens when the package is updated?
Will we have to change the code after every update?

Constructive critique here:
This popup is def not "Sublime-like"
One thing that make Sublime users use it on the first place is it's focus on content
Please, consider putting this feature behind a flag

**Comment by p-mcgowan** [comment]
Yes, you will likely have to make the changes again after the update. [PR-562](https://github.com/Microsoft/TypeScript-Sublime-Plugin/pull/562) looks like it will solve this problem.

**Comment by drdanmorris** [comment]
Yes, please remove the annoying red inline error boxes.  The TypeScript plugin is generally awesome, but this was an awful idea.  I'll be doing the manual script hack for now (thanks p-mcgowan) until sanity has prevailed.

**Comment by shudson250** [comment]
I've been looking for this solution in all the wrong places; anywhere but the Microsoft plugin. Bizarre addition to the plugin, and thanks p-mcgowan for the hack.

**Comment by distinctdan** [comment]
+1 for removing this, although my main issue is that it's popping up for errors that aren't really errors. For example, I have a line that reads: `public activeContainer: JQuery;`, which causes the plugin to error with "Cannot find name JQuery". However, my project compiles fine (I'm using grunt to do my compilation). I've included JQuery's .d.ts. Also, I'm not using the /// comment at the top of my files because the modern ts compiler doesn't need it, not sure if that matters.

**Comment by PWKad** [comment]
Dan that's a completely separate issue sublime isn't picking up your typings or perhaps even the tsconfig but your build is

**Comment by abenhamdine** [comment]
It's done, you can clone the current repo into your Packages folder.

**Comment by distinctdan** [comment]
Yup, thanks @PWKad, at first I didn't realize I needed a tsconfig since I wasn't using the build system and I didn't want to mess up my grunt process, but adding one did the trick.

Now about the popup, I do like that it's showing useful information in a relevant context. I think the main issue is the presentation. It feels weird that it shifts the text, and it's kind of annoying that it's big and red and not closable if I press escape.

I think it may work better as a tooltip that hovers under the offending line instead of an inline thing. Someone else mentioned a delay, which could be good, and it would also be nice if the tooltip line-wrapped, so if it's a really long error, you don't have to scroll horizontally.

**Comment by distinctdan** [comment]
Hey, just wanted to say thanks for fixing this. The new error tooltips are great.

**Comment by madneon** [comment]
What if I can't find TypeScript package and I have this annoying phantom popups? How to disable them?

**Comment by DanielRosenwasser** [comment]
@madneon Just ensure you upgrade using package control. You shouldn't get this behavior anymore.
