### ISSUE TITLE
Page up/down in intellisense menu

### ISSUE THREAD

**Issue by roblourens** [Microsoft/TypeScript-Sublime-Plugin#56]
I keep expecting page up/down to work in the intellisense menu because it can be very long. Instead it closes the menu and does page up/down on the document. This would just be nice to have.

**Comment by billti** [comment]
This is part of the Sublime UX, and our behavior here is consistent with Sublime.  You can up/down with the cursor (which admittedly isn't the best for a very long list), or start typing to narrow the list via fuzzy search.

If we get a lot of feedback we can think about augmenting the Sublime behavior here, otherwise it seems optimal to behave as 'native' as possible.
