### ISSUE TITLE
releases?

### ISSUE THREAD

**Issue by isaacl** [microsoft/TypeScript-Sublime-Plugin#763]
What is going on with this project? There's been important PRs merged since June and no release

**Comment by DanielRosenwasser** [comment]
Hey there, originally a release was slated around the time that TypeScript 4.0 had gone out; however, in trying out the recent changes locally, I couldn't get things working. Rather than publishing a potentially-breaking release, we opted not to publish at all, but haven't been able to dedicate the time to revisit yet.

**Comment by isaacl** [comment]
@DanielRosenwasser Can you do a minor release with #748?  It makes using typescript 4.0 locally much easier, and since README tracks master, the docs about this PR are shown even though it's not released.

**Comment by orta** [comment]
I've left some notes about the blocker in #765 - if you're familiar with ST extension development, it'd be great to help debug

**Comment by MatissJanis** [comment]
Any update here? Would be great to finally be able to use TS v4 without doing local hacks.

**Comment by orta** [comment]
No updates, you're welcome to look into it 👍🏻

**Comment by orta** [comment]
Confirmed that #767 fixes the issue with master on Windows - this is now un-blocked for release.

**Comment by talgat-ruby** [comment]
So when can you release now or are there still problems?

**Comment by DanielRosenwasser** [comment]
A release should be going out today. Thanks for the patience everyone!
