### ISSUE TITLE
Possible to show both errors and quick info if both info is available?

### ISSUE THREAD

**Issue by fionafung** [Microsoft/TypeScript-Sublime-Plugin#87]
I'm in the process of writing my class, and I wanted to bring up quick info in the status bar to help remind me of the right parameters.  Right now I only see the error that I'm not passing in the right parameters.  Is it possible to show both info if it's available?

![errorquickinfo](https://cloud.githubusercontent.com/assets/10522330/6835121/d8c8952e-d2f5-11e4-9981-01ef11809ed8.png)

**Comment by ddotlic** [comment]
This might be related to the bug I've just opened #172 - I'm not sure what the intent behind this bug is, but IIUC the editor should have popped up a "tooltip" with constructor arguments, same for any other method.

I'm confused because I've just seen video from Build in which this works just fine for Anders, but not for me, plus this bug is 'ancient' for the speed with which things progress around TypeScript.

Could someone please shed some light on this? Thanks!

**Comment by zhengbli** [comment]
Close because with tooltips available, the function signatures will be showed in tooltips and won't be conflicting with error info if they both exist.
